### ISSUE TITLE
Can't Use indexeddb-promise in Chrome Extension's background script

### ISSUE THREAD

**Issue by iammohan01** [n1md7/indexeddb-promise#19]
I tried to access idb operations from chrome extensions background script. But could not access

<img width="450" alt="Screenshot 2023-10-29 at 3 43 43 PM" src="https://github.com/n1md7/indexeddb-promise/assets/85432311/89097148-b16a-4771-813f-494a40514e85">

What i found is that we can't access window from background script , but we can acces indexedDB from background script

<img width="903" alt="Screenshot 2023-10-29 at 3 50 01 PM" src="https://github.com/n1md7/indexeddb-promise/assets/85432311/1a0ea677-18d1-4beb-9dbf-8cdd9d3bbc8d">

<img width="395" alt="Screenshot 2023-10-29 at 3 49 23 PM" src="https://github.com/n1md7/indexeddb-promise/assets/85432311/f456b7c7-5e41-48fa-a465-567b57ab5ba1">

**Comment by n1md7** [comment]
Hi, thanks for reporting.

I guess I've never thought to make it work for the chrome-extension environment.

I'll try to fix it as soon as I get a chance.
